<#include "/form.ftl">

<#assign mezzoFields = [
{
    "type":"hidden",
    "name":"id",
    "value":dettaglio.id!''
},
{
    "type":"text",
    "name":"nome",
    "label":"Nome",
    "value":dettaglio.nome!'',
    "readonly":true,
    "disabled":true
},
{
    "type":"textarea",
    "name":"descrizione",
    "label":"Descrizione",
    "value":dettaglio.descrizione!'',
    "rows":4,
    "readonly":true,
    "disabled":true
},
{
    "type":"text",
    "name":"targa",
    "label":"Targa",
    "value":dettaglio.targa!'',
    "readonly":true,
    "disabled":true
},
{
    "type":"text",
    "name":"stato",
    "label":"Stato",
    "value":dettaglio.stato!'',
    "readonly":true,
    "disabled":true
}
]>

<@form
    id="mezzoDeleteForm"
    csrfToken=csrfToken
    action="${ctx}/api/delete/mezzi"
    method="post"
    fields=mezzoFields
    submitLabel="Elimina"
    resetLabel="Annulla"
    cssClass="delete-modal"
/>
